# Generated by Django 5.2 on 2025-05-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='statementitem',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='statement',
            constraint=models.UniqueConstraint(fields=('account', 'date'), name='unique_account_date'),
        ),
    ]
